name: Generate ASCII Artwork

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Fetches repository code

      - name: Ensure script.sh is executable
        run: chmod +x script.sh  # Ensures the script has executable permissions

      - name: Execute script
        run: ./script.sh  # Runs the shell script

      - name: List Files in Workspace
        run: ls -l  # Lists all files in the workspace

  validate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Fetches repository code

      - name: Verify script execution
        run: |
          echo "Re-checking output from previous job:"
          ls -l  # Re-validates the state after build
